export * from './amazed.png';
export * from './cool.png';
export * from './happy.png';
export * from './mad.png';
export * from './meh.png';
export * from './No_answer.png';
export * from './sad.png';
export * from './tired.png';
export * from './very_happy.png';